// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: prefer_single_quotes

// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

class JsonSerializable {
  const JsonSerializable();
}

class JSONField {
  final String? name;

  final bool? serialize;

  final bool? deserialize;

  const JSONField({this.name, this.serialize, this.deserialize});
}
